INSERT INTO TRANSFER_REQUEST_STATUS (id, name) VALUES (1, 'CREATED_USER');
INSERT INTO TRANSFER_REQUEST_STATUS (id, name) VALUES (2, 'POSTED');
INSERT INTO TRANSFER_REQUEST_STATUS (id, name) VALUES (3, 'REVOKED');
INSERT INTO TRANSFER_REQUEST_STATUS (id, name) VALUES (4, 'POSTPONED_AS_VOUCHER');
INSERT INTO TRANSFER_REQUEST_STATUS (id, name) VALUES (5, 'REVOKED_ADMIN');