INSERT INTO INVOICE_OPERATION_DIRECTION (id, name) VALUES (1, 'REFILL');
INSERT INTO INVOICE_OPERATION_DIRECTION (id, name) VALUES (2, 'WITHDRAW');
INSERT INTO INVOICE_OPERATION_DIRECTION (id, name) VALUES (3, 'TRANSFER_VOUCHER');