INSERT INTO NEWS_TYPE (id, name) VALUES (1, 'NEWS');
INSERT INTO NEWS_TYPE (id, name) VALUES (2, 'MATERIALS');
INSERT INTO NEWS_TYPE (id, name) VALUES (3, 'WEBINAR');
INSERT INTO NEWS_TYPE (id, name) VALUES (4, 'VIDEO');
INSERT INTO NEWS_TYPE (id, name) VALUES (5, 'EVENT');
INSERT INTO NEWS_TYPE (id, name) VALUES (6, 'FEASTDAY');
INSERT INTO NEWS_TYPE (id, name) VALUES (7, 'PAGE');