INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (1, 10, 'BANK BCA', '014');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (2, 10, 'BANK MANDIRI', '008');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (3, 10, 'BANK BNI', '009');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (4, 10, 'BANK BRI', '002');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (5, 10, 'AMERICAN EXPRESS BANK LTD', '030');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (6, 10, 'ANGLOMAS INTERNASIONAL BANK', '531');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (7, 10, 'ANZ PANIN BANK', '061');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (8, 10, 'BANK ABN AMRO', '052');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (9, 10, 'BANK AGRO NIAGA', '494');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (10, 10, 'BANK AKITA', '525');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (11, 10, 'BANK ALFINDO', '503');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (12, 10, 'BANK ANTARDAERAH', '088');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (13, 10, 'BANK ARTA NIAGA KENCANA', '020');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (14, 10, 'BANK ARTHA GRAHA', '037');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (15, 10, 'BANK ARTOS IND', '542');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (16, 10, 'BANK BENGKULU', '133');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (17, 10, 'BANK BII', '016');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (18, 10, 'BANK BINTANG MANUNGGAL', '484');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (19, 10, 'BANK BISNIS INTERNASIONAL', '459');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (20, 10, 'BANK BNP PARIBAS INDONESIA', '057');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (21, 10, 'BANK BUANA IND', '023');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (22, 10, 'BANK BUKOPIN', '441');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (23, 10, 'BANK BUMI ARTA', '076');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (24, 10, 'BANK BUMIPUTERA', '485');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (25, 10, 'BANK CAPITAL INDONESIA, TBK.', '054');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (26, 10, 'BANK CENTURY, TBK.', '095');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (27, 10, 'BANK CHINA TRUST INDONESIA', '949');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (28, 10, 'BANK COMMONWEALTH', '950');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (29, 10, 'BANK CREDIT AGRICOLE INDOSUEZ', '039');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (30, 10, 'BANK DANAMON', '011');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (31, 10, 'BANK DBS INDONESIA', '046');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (32, 10, 'BANK DIPO INTERNATIONAL', '523');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (33, 10, 'BANK DKI', '111');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (34, 10, 'BANK EKONOMI', '087');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (35, 10, 'BANK EKSEKUTIF', '558');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (36, 10, 'BANK EKSPOR INDONESIA', '003');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (37, 10, 'BANK FAMA INTERNASIONAL', '562');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (38, 10, 'BANK FINCONESIA', '945');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (39, 10, 'BANK GANESHA', '161');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (40, 10, 'BANK HAGA', '089');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (41, 10, 'BANK HAGAKITA', '159');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (42, 10, 'BANK HARDA', '567');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (43, 10, 'BANK HARFA', '517');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (44, 10, 'BANK HARMONI INTERNATIONAL', '166');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (45, 10, 'BANK HIMPUNAN SAUDARA 1906, TBK.', '212');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (46, 10, 'BANK IFI', '093');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (47, 10, 'BANK INA PERDANA', '513');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (48, 10, 'BANK INDEX SELINDO', '555');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (49, 10, 'BANK INDOMONEX', '498');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (50, 10, 'BANK JABAR', '110');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (51, 10, 'BANK BRI SYARIAH', '422');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (52, 10, 'BANK JASA JAKARTA-427', '427');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (53, 10, 'BANK JASA JAKARTA-472', '472');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (54, 10, 'BANK JATENG', '113');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (55, 10, 'BANK JATIM', '114');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (56, 10, 'BANK KEPPEL TATLEE BUANA', '053');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (57, 10, 'BANK KESAWAN', '167');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (58, 10, 'BANK KESEJAHTERAAN EKONOMI', '535');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (59, 10, 'BANK LAMPUNG', '121');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (60, 10, 'BANK LIPPO', '026');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (61, 10, 'BANK MALUKU', '131');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (62, 10, 'BANK MASPION', '157');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (63, 10, 'BANK MAYAPADA', '097');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (64, 10, 'BANK MAYBANK INDOCORP', '947');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (65, 10, 'BANK MAYORA', '553');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (66, 10, 'BANK MEGA', '426');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (67, 10, 'BANK MERINCORP', '946');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (68, 10, 'BANK MESTIKA', '151');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (69, 10, 'BANK METRO EXPRESS', '152');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (70, 10, 'BANK MITRANIAGA', '491');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (71, 10, 'BANK MIZUHO INDONESIA', '048');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (72, 10, 'BANK MUAMALAT', '147');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (73, 10, 'BANK MULTI ARTA SENTOSA', '548');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (74, 10, 'BANK MULTICOR TBK.', '036');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (75, 10, 'BANK NAGARI', '118');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (76, 10, 'BANK NIAGA', '022');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (77, 10, 'BANK NISP', '028');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (78, 10, 'BANK NTT', '130');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (79, 10, 'BANK NUSANTARA PARAHYANGAN', '145');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (80, 10, 'BANK OCBC – INDONESIA', '948');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (81, 10, 'BANK OF AMERICA, N.A', '033');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (82, 10, 'BANK OF CHINA LIMITED', '069');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (83, 10, 'BANK PANIN', '019');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (84, 10, 'BANK PERSYARIKATAN INDONESIA', '521');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (85, 10, 'BANK PURBA DANARTA', '547');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (86, 10, 'BANK RESONA PERDANIA', '047');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (87, 10, 'BANK RIAU', '119');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (88, 10, 'BANK ROYAL INDONESIA', '501');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (89, 10, 'BANK SHINTA INDONESIA', '153');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (90, 10, 'BANK SINAR HARAPAN BALI', '564');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (91, 10, 'BANK SRI PARTHA', '466');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (92, 10, 'BANK SULTRA', '135');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (93, 10, 'BANK SULUT', '127');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (94, 10, 'BANK SUMITOMO MITSUI INDONESIA', '045');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (95, 10, 'BANK SUMSEL', '120');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (96, 10, 'BANK SUMUT', '117');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (97, 10, 'BANK SWADESI', '146');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (98, 10, 'BANK SWAGUNA', '405');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (99, 10, 'BANK SYARIAH MANDIRI', '451');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (100, 10, 'BANK SYARIAH MEGA', '506');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (101, 10, 'BANK TABUNGAN NEGARA PERSERO BTN', '200');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (102, 10, 'BANK TABUNGAN PENSIUNAN NASIONAL', '213');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (103, 10, 'BANK UIB', '536');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (104, 10, 'BANK UOB INDONESIA', '058');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (105, 10, 'BANK VICTORIA INTERNATIONAL', '566');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (106, 10, 'BANK WINDU KENTJANA', '162');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (107, 10, 'BANK WOORI INDONESIA', '068');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (108, 10, 'BANK YUDHA BHAKTI', '490');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (109, 10, 'BPD ACEH', '116');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (110, 10, 'BPD BALI', '129');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (111, 10, 'BPD DIY', '112');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (112, 10, 'BPD JAMBI', '115');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (113, 10, 'BPD KALIMANTAN BARAT', '123');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (114, 10, 'BPD KALSEL', '122');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (115, 10, 'BPD KALTENG', '125');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (116, 10, 'BPD KALTIM', '124');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (117, 10, 'BPD NTB', '128');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (118, 10, 'BPD PAPUA', '132');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (119, 10, 'BPD SULAWESI TENGAH', '134');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (120, 10, 'BPD SULSEL', '126');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (121, 10, 'CENTRATAMA NASIONAL BANK', '559');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (122, 10, 'CITIBANK N.A.', '031');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (123, 10, 'DEUTSCHE BANK AG.', '067');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (124, 10, 'HALIM INDONESIA BANK', '164');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (125, 10, 'ING INDONESIA BANK', '034');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (126, 10, 'JP. MORGAN CHASE BANK, N.A.', '032');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (127, 10, 'KOREA EXCHANGE BANK DANAMON', '059');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (128, 10, 'LIMAN INTERNATIONAL BANK', '526');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (129, 10, 'PERMATA BANK', '013');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (130, 10, 'PRIMA MASTER BANK', '520');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (131, 10, 'RABOBANK INTERNASIONAL INDONESIA', '060');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (132, 10, 'STANDARD CHARTERED BANK', '050');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (133, 10, 'THE BANGKOK BANK COMP. LTD', '040');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (134, 10, 'THE BANK OF TOKYO MITSUBISHI UFJ LTD', '042');
INSERT INTO CLIENT_BANK (id, currency_id, name, code) VALUES (135, 10, 'THE HONGKONG & SHANGHAI B.C.', '041');