INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (1, 'Aland Islands', 'AX');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (2, 'Albania', 'AL');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (3, 'Algeria', 'DZ');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (4, 'American Samoa', 'AS');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (5, 'Andorra', 'AD');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (6, 'Angola', 'AO');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (7, 'Anguilla', 'AI');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (8, 'Antarctica', 'AQ');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (9, 'Antigua and Barbuda', 'AG');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (10, 'Argentina', 'AR');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (11, 'Armenia', 'AM');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (12, 'Aruba', 'AW');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (13, 'Australia', 'AU');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (14, 'Austria', 'AT');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (15, 'Azerbaijan', 'AZ');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (16, 'Bahamas', 'BS');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (17, 'Bahrain', 'BH');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (18, 'Bangladesh', 'BD');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (19, 'Barbados', 'BB');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (20, 'Belarus', 'BY');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (21, 'Belgium', 'BE');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (22, 'Belize', 'BZ');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (23, 'Benin', 'BJ');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (24, 'Bermuda', 'BM');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (25, 'Bhutan', 'BT');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (26, 'Bolivia', 'BO');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (27, 'Bosnia and Herzegovina', 'BA');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (28, 'Botswana', 'BW');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (29, 'Bouvet Island', 'BV');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (30, 'Brazil', 'BR');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (31, 'British Indian Ocean Territory', 'IO');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (32, 'Brunei', 'BN');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (33, 'Bulgaria', 'BG');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (34, 'Burkina Faso', 'BF');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (35, 'Burma (Myanmar)', 'MM');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (36, 'Burundi', 'BI');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (37, 'Cambodia', 'KH');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (38, 'Cameroon', 'CM');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (39, 'Canada', 'CA');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (40, 'Cape Verde', 'CV');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (41, 'Cayman Islands', 'KY');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (42, 'Central African Republic', 'CF');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (43, 'Chad', 'TD');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (44, 'Chile', 'CL');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (45, 'China', 'CN');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (46, 'Christmas Island', 'CX');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (47, 'Cocos (Keeling) Islands', 'CC');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (48, 'Colombia', 'CO');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (49, 'Comoros', 'KM');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (50, 'Congo,  Dem. Republic', 'CD');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (51, 'Congo,  Republic', 'CG');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (52, 'Cook Islands', 'CK');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (53, 'Costa Rica', 'CR');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (54, 'Croatia', 'HR');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (55, 'Cuba', 'CU');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (56, 'Cyprus', 'CY');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (57, 'Czech Republic', 'CZ');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (58, 'Denmark', 'DK');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (59, 'Djibouti', 'DJ');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (60, 'Dominica', 'DM');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (61, 'Dominican Republic', 'DO');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (62, 'East Timor', 'TL');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (63, 'Ecuador', 'EC');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (64, 'Egypt', 'EG');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (65, 'El Salvador', 'SV');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (66, 'Equatorial Guinea', 'GQ');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (67, 'Eritrea', 'ER');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (68, 'Estonia', 'EE');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (69, 'Ethiopia', 'ET');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (70, 'Falkland Islands', 'FK');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (71, 'Faroe Islands', 'FO');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (72, 'Fiji', 'FJ');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (73, 'Finland', 'FI');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (74, 'France', 'FR');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (75, 'French Guiana', 'GF');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (76, 'French Polynesia', 'PF');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (77, 'French Southern Territories', 'TF');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (78, 'Gabon', 'GA');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (79, 'Gambia', 'GM');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (80, 'Georgia', 'GE');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (81, 'Germany', 'DE');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (82, 'Ghana', 'GH');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (83, 'Gibraltar', 'GI');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (84, 'Greece', 'GR');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (85, 'Greenland', 'GL');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (86, 'Grenada', 'GD');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (87, 'Guadeloupe', 'GP');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (88, 'Guam', 'GU');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (89, 'Guatemala', 'GT');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (90, 'Guernsey', 'GG');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (91, 'Guinea', 'GN');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (92, 'Guinea-Bissau', 'GW');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (93, 'Guyana', 'GY');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (94, 'Haiti', 'HT');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (95, 'Heard Island and McDonald Islands', 'HM');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (96, 'Honduras', 'HN');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (97, 'HongKong', 'HK');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (98, 'Hungary', 'HU');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (99, 'Iceland', 'IS');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (100, 'India', 'IN');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (101, 'Indonesia', 'ID');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (102, 'Iran', 'IR');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (103, 'Iraq', 'IQ');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (104, 'Ireland', 'IE');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (105, 'Israel', 'IL');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (106, 'Italy', 'IT');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (107, 'Ivory Coast', 'CI');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (108, 'Jamaica', 'JM');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (109, 'Japan', 'JP');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (110, 'Jersey', 'JE');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (111, 'Jordan', 'JO');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (112, 'Kazakhstan', 'KZ');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (113, 'Kenya', 'KE');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (114, 'Kiribati', 'KI');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (115, 'Korea,  Dem. Republic of', 'KP');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (116, 'Kuwait', 'KW');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (117, 'Kyrgyzstan', 'KG');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (118, 'Laos', 'LA');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (119, 'Latvia', 'LV');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (120, 'Lebanon', 'LB');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (121, 'Lesotho', 'LS');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (122, 'Liberia', 'LR');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (123, 'Libya', 'LY');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (124, 'Liechtenstein', 'LI');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (125, 'Lithuania', 'LT');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (126, 'Luxemburg', 'LU');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (127, 'Macau', 'MO');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (128, 'Macedonia', 'MK');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (129, 'Madagascar', 'MG');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (130, 'Malawi', 'MW');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (131, 'Malaysia', 'MY');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (132, 'Maldives', 'MV');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (133, 'Mali', 'ML');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (134, 'Malta', 'MT');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (135, 'Man Island', 'IM');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (136, 'Marshall Islands', 'MH');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (137, 'Martinique', 'MQ');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (138, 'Mauritania', 'MR');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (139, 'Mauritius', 'MU');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (140, 'Mayotte', 'YT');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (141, 'Mexico', 'MX');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (142, 'Micronesia', 'FM');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (143, 'Moldova', 'MD');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (144, 'Monaco', 'MC');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (145, 'Mongolia', 'MN');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (146, 'Montenegro', 'ME');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (147, 'Montserrat', 'MS');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (148, 'Morocco', 'MA');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (149, 'Mozambique', 'MZ');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (150, 'Namibia', 'NA');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (151, 'Nauru', 'NR');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (152, 'Nepal', 'NP');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (153, 'Netherlands', 'NL');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (154, 'Netherlands Antilles', 'AN');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (155, 'New Caledonia', 'NC');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (156, 'New Zealand', 'NZ');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (157, 'Nicaragua', 'NI');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (158, 'Niger', 'NE');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (159, 'Nigeria', 'NG');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (160, 'Niue', 'NU');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (161, 'Norfolk Island', 'NF');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (162, 'Northern Mariana Islands', 'MP');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (163, 'Norway', 'NO');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (164, 'Oman', 'OM');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (165, 'Pakistan', 'PK');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (166, 'Palau', 'PW');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (167, 'Palestinian Territories', 'PS');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (168, 'Panama', 'PA');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (169, 'Papua New Guinea', 'PG');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (170, 'Paraguay', 'PY');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (171, 'Peru', 'PE');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (172, 'Philippines', 'PH');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (173, 'Pitcairn', 'PN');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (174, 'Poland', 'PL');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (175, 'Portugal', 'PT');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (176, 'Puerto Rico', 'PR');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (177, 'Qatar', 'QA');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (178, 'Reunion Island', 'RE');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (179, 'Romania', 'RO');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (180, 'Russian Federation', 'RU');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (181, 'Rwanda', 'RW');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (182, 'Saint Barthelemy', 'BL');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (183, 'Saint Kitts and Nevis', 'KN');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (184, 'Saint Lucia', 'LC');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (185, 'Saint Martin', 'MF');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (186, 'Saint Pierre and Miquelon', 'PM');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (187, 'Saint Vincent and the Grenadines', 'VC');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (188, 'Samoa', 'WS');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (189, 'San Marino', 'SM');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (190, 'Saudi Arabia', 'SA');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (191, 'Senegal', 'SN');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (192, 'Serbia', 'RS');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (193, 'Seychelles', 'SC');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (194, 'Sierra Leone', 'SL');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (195, 'Singapore', 'SG');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (196, 'Slovakia', 'SK');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (197, 'Slovenia', 'SI');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (198, 'Solomon Islands', 'SB');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (199, 'Somalia', 'SO');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (200, 'South Africa', 'ZA');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (201, 'South Georgia and the South Sandwich Islands', 'GS');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (202, 'South Korea', 'KR');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (203, 'Spain', 'ES');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (204, 'Sri Lanka', 'LK');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (205, 'Sudan', 'SD');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (206, 'Suriname', 'SR');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (207, 'Svalbard and Jan Mayen', 'SJ');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (208, 'Swaziland', 'SZ');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (209, 'Sweden', 'SE');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (210, 'Switzerland', 'CH');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (211, 'Syria', 'SY');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (212, 'São Tomé and Príncipe', 'ST');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (213, 'Taiwan', 'TW');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (214, 'Tajikistan', 'TJ');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (215, 'Tanzania', 'TZ');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (216, 'Thailand', 'TH');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (217, 'Togo', 'TG');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (218, 'Tokelau', 'TK');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (219, 'Tonga', 'TO');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (220, 'Trinidad and Tobago', 'TT');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (221, 'Tunisia', 'TN');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (222, 'Turkey', 'TR');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (223, 'Turkmenistan', 'TM');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (224, 'Turks and Caicos Islands', 'TC');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (225, 'Tuvalu', 'TV');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (226, 'Uganda', 'UG');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (227, 'Ukraine', 'UA');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (228, 'United Arab Emirates', 'AE');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (229, 'United Kingdom', 'GB');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (230, 'United States', 'US');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (231, 'Uruguay', 'UY');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (232, 'Uzbekistan', 'UZ');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (233, 'Vanuatu', 'VU');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (234, 'Vatican City State', 'VA');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (235, 'Venezuela', 'VE');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (236, 'Vietnam', 'VN');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (237, 'Virgin Islands (British)', 'VG');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (238, 'Virgin Islands (U.S.)', 'VI');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (239, 'Wallis and Futuna', 'WF');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (240, 'Western Sahara', 'EH');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (241, 'Yemen', 'YE');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (242, 'Zambia', 'ZM');
INSERT INTO KYC_COUNTRY_CODES (id, country_name, country_code) VALUES (243, 'Zimbabwe', 'ZW');