ALTER TABLE WITHDRAW_REQUEST ADD column analytic_holder_id  INT;

ALTER TABLE WITHDRAW_REQUEST ADD CONSTRAINT fk_analytic_holder_id FOREIGN KEY (analytic_holder_id) REFERENCES USER (id);

INSERT INTO WITHDRAW_REQUEST_STATUS (id, name)
VALUES  (22, 'WAITING_ANALYTICS_CONFIRMATION_FOR_MANUAL'),
        (23, 'WAITING_ANALYTICS_CONFIRMATION_FOR_SEMI_AUTO'),
        (24, 'IN_WORK_OF_ANALYTICS_FOR_MANUAL'),
        (25, 'IN_WORK_OF_ANALYTICS_SEMI_AUTO'),
        (28, 'DECLINED_ANALYTICS_MANUAL'),
        (29, 'DECLINED_ANALYTICS_SEMI_AUTO');