CREATE TABLE IF NOT EXISTS KYC(
id INT(40) NOT NULL AUTO_INCREMENT,
kyc_type ENUM('INDIVIDUAL', 'LEGAL_ENTITY'),
kyc_status ENUM('IN_PROGRESS', 'NEED_CHECK', 'REJECTED', 'APPROVED', 'NOT_VERIFIED'),
company_name VARCHAR(45),
reg_country VARCHAR(45),
reg_number VARCHAR(45),
commercial_registry_path VARCHAR(100),
company_charter_path VARCHAR(100),
address_id INT(40),
person_id INT(40),
user_id INT(40),
admin VARCHAR(45),
PRIMARY KEY (id)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


CREATE TABLE IF NOT EXISTS KYC_PERSON (
id INT(40) NOT NULL AUTO_INCREMENT,
position VARCHAR(100),
name VARCHAR(45),
surname VARCHAR(45),
middle_name VARCHAR(45),
phone VARCHAR(45),
confirm_document_path VARCHAR(100),
nationality VARCHAR(45),
id_number VARCHAR(45),
gender ENUM('MALE', 'FEMALE'),
birth_date VARCHAR(45),
PRIMARY KEY(id)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


CREATE TABLE IF NOT EXISTS KYC_ADDRESS(
id INT(40) NOT NULL AUTO_INCREMENT,
country VARCHAR(45),
city VARCHAR(45),
street VARCHAR(45),
zip_code VARCHAR(45),
PRIMARY KEY (id)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


CREATE TABLE IF NOT EXISTS WORLD_CHECK(
id INT(40) NOT NULL AUTO_INCREMENT,
world_check_status ENUM('IN_PROGRESS', 'NEED_CHECK', 'REJECTED', 'APPROVED', 'NOT_VERIFIED'),
user_id INT(40),
admin VARCHAR(45),
PRIMARY KEY (id)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;