DROP PROCEDURE IF EXISTS GET_COINMARKETCAP_STATISTICS;
DROP PROCEDURE IF EXISTS GET_CURRENCY_PAIR_STATISTICS_FOR_CACHE;
DROP PROCEDURE IF EXISTS GET_DATA_FOR_CANDLE;
DROP PROCEDURE IF EXISTS GET_DATA_FOR_CANDLE_RANGE;