CREATE TABLE IF NOT EXISTS GTAG_REFILL_REQUESTS
(
  USER_ID INT NOT NULL,
  COUNT   INT,
  CONSTRAINT PK_ID PRIMARY KEY (USER_ID),
  CONSTRAINT `FOREIGN_KEY` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`id`)
);
