CREATE TABLE IF NOT EXISTS CONTROL_PHRASE (
  'id'        INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  'phrase'    VARCHAR(20)   NOT NULL DEFAULT '',
  'user_id'   INT UNSIGNED  NOT NULL UNIQUE,
  CONSTRAINT user_id_fk FOREIGN KEY (user_id) REFERENCES USER_ROLE (id)
) CHARACTER SET utf8 COLLATE utf8_general_ci;